config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  post 'pictures' => 'pictures#create'

  resources :pictures

  patch 'pictures/:id' => "pictures#update"

  delete 'pictures/:id' => 'pictures#destroy', as: "delete_picture"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  scope :newest_first, -> { order(created_at: 'desc')}
  scope :most_recent_five, -> { newest_first.limit(5) }

  scope :created_before, ->(time) { where("created_at < ?", time) }

  def self.newest_first
    order(created_at: 'desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.most_recent_five
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_url
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

  private
  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>
<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @pictures.length %>)</h1>
<%= link_to "New Picture", "/pictures/new" %>

<% @pictures.each do |picture| %>
  <p><%= picture.title %>, <%= picture.artist %></p>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a Picture</h1>
<%= link_to "Back to Pictures", pictures_url %>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", delete_picture_path(@picture), method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>

<p><%= @picture.title %>, <%= @picture.artist %></p>
<%= image_tag @picture.url %>